### How to Create List in Python

In [2]:
L=list(range(10))

In [3]:
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [9]:
import array
L = list(range(10))
A = array.array('i', L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
import numpy as np

In [13]:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [14]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [15]:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [16]:
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [17]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [18]:
np.arange(0,20,3)


array([ 0,  3,  6,  9, 12, 15, 18])

In [19]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [21]:
x = np.arange(4)
print("x     =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2)

x     = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]


In [24]:
np.add(x,8)

array([ 8,  9, 10, 11])

In [1]:
import numpy as np
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)
min(big_array), max(big_array)

421 ms ± 20.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
2.18 ms ± 105 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


(2.973845312226331e-07, 0.9999998872092567)

In [2]:
np.min(big_array), np.max(big_array)

(2.973845312226331e-07, 0.9999998872092567)

In [3]:
%timeit min(big_array)
%timeit np.min(big_array)
print(big_array.min(), big_array.max(), big_array.sum())

266 ms ± 11.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
921 µs ± 16.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
2.973845312226331e-07 0.9999998872092567 500232.92993052665
